/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notes' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'topics' : IDL.Vec(Topic),
});
export const InterviewQuestion = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const TimelineEntry = IDL.Record({
  'day' : IDL.Nat,
  'activity' : IDL.Text,
});
export const InterviewPrepContent = IDL.Record({
  'jobRole' : IDL.Text,
  'questions' : IDL.Vec(InterviewQuestion),
  'twoDayTimeline' : IDL.Vec(TimelineEntry),
});
export const Content = IDL.Record({
  'interviewPrepContent' : IDL.Vec(InterviewPrepContent),
  'chapters' : IDL.Vec(Chapter),
});

export const idlService = IDL.Service({
  'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
  'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getInterviewPrepContent' : IDL.Func(
      [IDL.Text],
      [InterviewPrepContent],
      ['query'],
    ),
  'isTopicComplete' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'markTopicComplete' : IDL.Func([IDL.Nat], [], []),
  'seedContent' : IDL.Func([Content], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'topics' : IDL.Vec(Topic),
  });
  const InterviewQuestion = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const TimelineEntry = IDL.Record({ 'day' : IDL.Nat, 'activity' : IDL.Text });
  const InterviewPrepContent = IDL.Record({
    'jobRole' : IDL.Text,
    'questions' : IDL.Vec(InterviewQuestion),
    'twoDayTimeline' : IDL.Vec(TimelineEntry),
  });
  const Content = IDL.Record({
    'interviewPrepContent' : IDL.Vec(InterviewPrepContent),
    'chapters' : IDL.Vec(Chapter),
  });
  
  return IDL.Service({
    'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
    'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getInterviewPrepContent' : IDL.Func(
        [IDL.Text],
        [InterviewPrepContent],
        ['query'],
      ),
    'isTopicComplete' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'markTopicComplete' : IDL.Func([IDL.Nat], [], []),
    'seedContent' : IDL.Func([Content], [], []),
  });
};

export const init = ({ IDL }) => { return []; };