/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'topics' : Array<Topic>,
}
export interface Content {
  'interviewPrepContent' : Array<InterviewPrepContent>,
  'chapters' : Array<Chapter>,
}
export interface InterviewPrepContent {
  'jobRole' : string,
  'questions' : Array<InterviewQuestion>,
  'twoDayTimeline' : Array<TimelineEntry>,
}
export interface InterviewQuestion { 'question' : string, 'answer' : string }
export interface TimelineEntry { 'day' : bigint, 'activity' : string }
export interface Topic { 'id' : bigint, 'title' : string, 'notes' : string }
export interface UserProfile { 'name' : string }
export type ApprovalStatus = { 'approved' : null } | { 'rejected' : null } | { 'pending' : null };
export type UserRole = { 'admin' : null } | { 'user' : null } | { 'guest' : null };
export interface UserApprovalInfo {
  'principal' : Principal,
  'status' : ApprovalStatus,
}
export interface _SERVICE {
  'getChapterById' : ActorMethod<[bigint], Chapter>,
  'getChapters' : ActorMethod<[], Array<Chapter>>,
  'getInterviewPrepContent' : ActorMethod<[string], InterviewPrepContent>,
  'isTopicComplete' : ActorMethod<[bigint], boolean>,
  'markTopicComplete' : ActorMethod<[bigint], undefined>,
  'seedContent' : ActorMethod<[Content], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'getAllUserApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'approveUser' : ActorMethod<[Principal], undefined>,
  'rejectUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
