/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notes' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'topics' : IDL.Vec(Topic),
});
export const InterviewQuestion = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const TimelineEntry = IDL.Record({ 'day' : IDL.Nat, 'activity' : IDL.Text });
export const InterviewPrepContent = IDL.Record({
  'jobRole' : IDL.Text,
  'questions' : IDL.Vec(InterviewQuestion),
  'twoDayTimeline' : IDL.Vec(TimelineEntry),
});
export const Content = IDL.Record({
  'interviewPrepContent' : IDL.Vec(InterviewPrepContent),
  'chapters' : IDL.Vec(Chapter),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'pending' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'principal' : IDL.Principal,
  'status' : ApprovalStatus,
});

export const idlService = IDL.Service({
  'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
  'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getInterviewPrepContent' : IDL.Func([IDL.Text], [InterviewPrepContent], ['query']),
  'isTopicComplete' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'markTopicComplete' : IDL.Func([IDL.Nat], [], []),
  'seedContent' : IDL.Func([Content], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllUserApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'topics' : IDL.Vec(Topic),
  });
  const InterviewQuestion = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
  });
  const TimelineEntry = IDL.Record({ 'day' : IDL.Nat, 'activity' : IDL.Text });
  const InterviewPrepContent = IDL.Record({
    'jobRole' : IDL.Text,
    'questions' : IDL.Vec(InterviewQuestion),
    'twoDayTimeline' : IDL.Vec(TimelineEntry),
  });
  const Content = IDL.Record({
    'interviewPrepContent' : IDL.Vec(InterviewPrepContent),
    'chapters' : IDL.Vec(Chapter),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'pending' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'principal' : IDL.Principal,
    'status' : ApprovalStatus,
  });

  return IDL.Service({
    'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
    'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getInterviewPrepContent' : IDL.Func([IDL.Text], [InterviewPrepContent], ['query']),
    'isTopicComplete' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'markTopicComplete' : IDL.Func([IDL.Nat], [], []),
    'seedContent' : IDL.Func([Content], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllUserApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
