/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Topic {
    id: bigint;
    title: string;
    notes: string;
}
export interface InterviewPrepContent {
    jobRole: string;
    questions: Array<InterviewQuestion>;
    twoDayTimeline: Array<TimelineEntry>;
}
export interface TimelineEntry {
    day: bigint;
    activity: string;
}
export interface InterviewQuestion {
    question: string;
    answer: string;
}
export interface Content {
    interviewPrepContent: Array<InterviewPrepContent>;
    chapters: Array<Chapter>;
}
export interface Chapter {
    id: bigint;
    title: string;
    topics: Array<Topic>;
}
export interface UserProfile {
    name: string;
}
export type ApprovalStatus = { __kind__: "approved" } | { __kind__: "rejected" } | { __kind__: "pending" };
export type UserRole = { __kind__: "admin" } | { __kind__: "user" } | { __kind__: "guest" };
export interface UserApprovalInfo {
    principal: Principal;
    status: ApprovalStatus;
}
export interface backendInterface {
    getChapterById(id: bigint): Promise<Chapter>;
    getChapters(): Promise<Array<Chapter>>;
    getInterviewPrepContent(jobRole: string): Promise<InterviewPrepContent>;
    isTopicComplete(topicId: bigint): Promise<boolean>;
    markTopicComplete(topicId: bigint): Promise<void>;
    seedContent(newContent: Content): Promise<void>;
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerApproved(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    getAllUserApprovals(): Promise<Array<UserApprovalInfo>>;
    approveUser(user: Principal): Promise<void>;
    rejectUser(user: Principal): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    private async _call<T>(fn: () => Promise<T>): Promise<T> {
        if (this.processError) {
            try {
                return await fn();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        }
        return fn();
    }
    async getChapterById(arg0: bigint): Promise<Chapter> {
        return this._call(() => this.actor.getChapterById(arg0));
    }
    async getChapters(): Promise<Array<Chapter>> {
        return this._call(() => this.actor.getChapters());
    }
    async getInterviewPrepContent(arg0: string): Promise<InterviewPrepContent> {
        return this._call(() => this.actor.getInterviewPrepContent(arg0));
    }
    async isTopicComplete(arg0: bigint): Promise<boolean> {
        return this._call(() => this.actor.isTopicComplete(arg0));
    }
    async markTopicComplete(arg0: bigint): Promise<void> {
        return this._call(() => this.actor.markTopicComplete(arg0));
    }
    async seedContent(arg0: Content): Promise<void> {
        return this._call(() => this.actor.seedContent(arg0));
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        return this._call(() => this.actor._initializeAccessControlWithSecret(arg0));
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        return this._call(() => this.actor.saveCallerUserProfile(arg0));
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        const result = await this._call(() => this.actor.getCallerUserProfile());
        // Candid returns opt as [] | [T]
        if (Array.isArray(result)) {
            return result.length > 0 ? result[0] : null;
        }
        return result ?? null;
    }
    async getCallerUserRole(): Promise<UserRole> {
        const raw = await this._call(() => this.actor.getCallerUserRole());
        // Convert Candid variant { admin: null } to { __kind__: "admin" }
        if (raw && typeof raw === 'object' && !('__kind__' in raw)) {
            const key = Object.keys(raw)[0];
            return { __kind__: key } as UserRole;
        }
        return raw as UserRole;
    }
    async isCallerApproved(): Promise<boolean> {
        return this._call(() => this.actor.isCallerApproved());
    }
    async isCallerAdmin(): Promise<boolean> {
        return this._call(() => this.actor.isCallerAdmin());
    }
    async getAllUserApprovals(): Promise<Array<UserApprovalInfo>> {
        const results = await this._call(() => this.actor.getAllUserApprovals());
        return results.map((item: any) => ({
            principal: item.principal,
            status: (() => {
                if ('__kind__' in item.status) return item.status;
                const key = Object.keys(item.status)[0];
                return { __kind__: key };
            })(),
        }));
    }
    async approveUser(arg0: Principal): Promise<void> {
        return this._call(() => this.actor.approveUser(arg0));
    }
    async rejectUser(arg0: Principal): Promise<void> {
        return this._call(() => this.actor.rejectUser(arg0));
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
